/**
 * Minimal FHIR mapping helpers for Allergy Detail page.
 * These functions produce example FHIR resources (AllergyIntolerance,
 * MedicationStatement) suitable for export or quick inspection.
 *
 * NOTE: This is a lightweight mapper for demo purposes only — a
 * production integration should use authoritative code systems
 * (SNOMED, RxNorm) and follow local IG requirements.
 */

export function mapAllergySummaryToFHIR(patient: any) {
  const now = new Date().toISOString();

  // If patient has explicit allergies, map each to an AllergyIntolerance
  const allergies = (patient.allergies || []).map((a: string, i: number) => ({
    resourceType: 'AllergyIntolerance',
    id: `allergy-${patient.id}-${i}`,
    clinicalStatus: { coding: [{ system: 'http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical', code: 'active' }], text: 'Active' },
    verificationStatus: { coding: [{ system: 'http://terminology.hl7.org/CodeSystem/allergyintolerance-verification', code: 'confirmed' }], text: 'Confirmed' },
    patient: { reference: `Patient/${patient.id}`, display: patient.name },
    code: { text: a },
    note: [{ text: 'Imported from EHR demo patient record' }],
  }));

  // If no allergies documented, create an explicit 'no known allergies' assertion
  if (allergies.length === 0) {
    allergies.push({
      resourceType: 'AllergyIntolerance',
      id: `allergy-${patient.id}-no-known`,
      clinicalStatus: { coding: [{ system: 'http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical', code: 'inactive' }], text: 'No known allergies' },
      verificationStatus: { coding: [{ system: 'http://terminology.hl7.org/CodeSystem/allergyintolerance-verification', code: 'confirmed' }], text: 'Verified' },
      patient: { reference: `Patient/${patient.id}`, display: patient.name },
      code: { coding: [{ system: 'http://snomed.info/sct', code: '39579001', display: 'No known allergy' }], text: 'No known allergies' },
      recordedDate: now,
      recorder: { display: patient.lastAttendingDoctor || 'Unknown' },
      note: [{ text: `No known allergies asserted on ${now}` }],
    });
  }

  // Map current medications to MedicationStatement resources for context
  const meds = (patient.medications || []).map((m: any, i: number) => ({
    resourceType: 'MedicationStatement',
    id: `med-${patient.id}-${i}`,
    status: 'active',
    medicationCodeableConcept: { text: m.name },
    subject: { reference: `Patient/${patient.id}`, display: patient.name },
    dosage: [{ text: `${m.dose || ''} ${m.freq || ''}` }],
  }));

  // Bundle
  const bundle: any = {
    resourceType: 'Bundle',
    type: 'document',
    timestamp: now,
    entry: [
      { resource: { resourceType: 'Patient', id: patient.id, name: [{ text: patient.name }], birthDate: patient.dob, identifier: [{ system: 'urn:mrn', value: patient.mrn }] } },
      ...allergies.map((r: any) => ({ resource: r })),
      ...meds.map((r: any) => ({ resource: r })),
    ],
  };

  return bundle;
}

/**
 * Map a risk profile summary to a minimal FHIR Bundle containing a RiskAssessment
 * and supporting Patient resource. This is a demo mapping for interoperability review.
 */
export function mapRiskProfileToFHIR(patient: { id: string; name?: string; mrn?: string; dob?: string }, riskProfile: { score: number; category: string; contributors?: Array<{ factor: string; weight: number; impact: string }>; generatedAt?: string; engineVersion?: string }) {
  const now = new Date().toISOString();
  const generated = riskProfile.generatedAt || now;

  const riskAssessment: any = {
    resourceType: 'RiskAssessment',
    id: `risk-${patient.id}`,
    status: 'final',
    subject: { reference: `Patient/${patient.id}`, display: patient.name },
    occurrenceDateTime: generated,
    prediction: [
      {
        outcome: { text: riskProfile.category },
        probabilityDecimal: (riskProfile.score || 0) / 100,
        qualitativeRisk: { text: riskProfile.category },
      },
    ],
    note: [{ text: `Risk score ${riskProfile.score} generated by engine ${riskProfile.engineVersion || 'unknown'}` }],
  };

  // Attach contributors as extensions in a lightweight form
  if (Array.isArray(riskProfile.contributors)) {
    riskAssessment.extension = riskProfile.contributors.map((c) => ({ url: `http://example.org/fhir/StructureDefinition/risk-contributor`, extension: [{ url: 'factor', valueString: c.factor }, { url: 'weight', valueDecimal: c.weight }, { url: 'impact', valueString: c.impact }] }));
  }

  const bundle: any = {
    resourceType: 'Bundle',
    type: 'document',
    timestamp: now,
    entry: [
      { resource: { resourceType: 'Patient', id: patient.id, name: [{ text: patient.name }], birthDate: patient.dob, identifier: patient.mrn ? [{ system: 'urn:mrn', value: patient.mrn }] : [] } },
      { resource: riskAssessment },
    ].filter(Boolean),
  };

  return bundle;
}

/**
 * Create a minimal medical history bundle composed of Patient, AllergyIntolerance,
 * Immunization, Encounter and DocumentReference resources for demo/export.
 */
export function mapMedicalHistoryToFHIR(patient: any) {
  const now = new Date().toISOString();

  const patientResource: any = {
    resourceType: 'Patient',
    id: patient.id,
    name: [{ text: patient.name }],
    birthDate: patient.dob,
    identifier: patient.mrn ? [{ system: 'urn:mrn', value: patient.mrn }] : [],
  };

  const allergies = (patient.allergies || []).map((a: any, i: number) => ({ resourceType: 'AllergyIntolerance', id: `allergy-${i}`, patient: { reference: `Patient/${patient.id}` }, code: { text: a } }));
  const immunizations = (patient.immunizations || []).map((im: any, i: number) => ({ resourceType: 'Immunization', id: `imm-${i}`, status: im.status || 'completed', vaccineCode: { text: im.name }, occurrenceDateTime: im.date, patient: { reference: `Patient/${patient.id}` } }));
  const encounters = (patient.history || []).map((e: any, i: number) => ({ resourceType: 'Encounter', id: `enc-${i}`, status: e.status || 'finished', class: { code: e.type || 'ambulatory' }, subject: { reference: `Patient/${patient.id}` }, period: { start: e.date } }));
  const documents = (patient.documents || []).map((d: any, i: number) => ({ resourceType: 'DocumentReference', id: d.fhirId || `doc-${i}`, status: d.status || 'current', type: { text: d.type || d.name }, indexed: d.date || now, subject: { reference: `Patient/${patient.id}` } }));

  const bundle: any = {
    resourceType: 'Bundle',
    type: 'document',
    timestamp: now,
    entry: [
      { resource: patientResource },
      ...allergies.map((r: any) => ({ resource: r })),
      ...immunizations.map((r: any) => ({ resource: r })),
      ...encounters.map((r: any) => ({ resource: r })),
      ...documents.map((r: any) => ({ resource: r })),
    ],
  };

  return bundle;
}

/**
 * Map current health concerns to a minimal FHIR Bundle (Patient + Condition resources)
 */
export function mapCurrentConcernsToFHIR(patient: any, concerns: any[]) {
  const now = new Date().toISOString();
  const patientRes: any = { resourceType: 'Patient', id: patient.id, name: [{ text: patient.name }], birthDate: patient.dob, identifier: patient.mrn ? [{ system: 'urn:mrn', value: patient.mrn }] : [] };

  const conditions = (concerns || []).map((c: any, i: number) => ({ resourceType: 'Condition', id: `condition-${i}`, clinicalStatus: { text: c.status || 'active' }, code: { text: c.name }, subject: { reference: `Patient/${patient.id}` }, recordedDate: c.firstNoted || now }));

  const bundle: any = { resourceType: 'Bundle', type: 'document', timestamp: now, entry: [{ resource: patientRes }, ...conditions.map((r:any)=>({ resource: r }))] };
  return bundle;
}

/**
 * Map trend series and observations to a FHIR Bundle for inspection/export.
 * Produces Observation resources and a containing Bundle with a Patient entry.
 */
export function mapTrendsToFHIR(patient: any, series: any[]) {
  const now = new Date().toISOString();
  const patientRes: any = { resourceType: 'Patient', id: patient.id, name: [{ text: patient.name }], birthDate: patient.dob, identifier: patient.mrn ? [{ system: 'urn:mrn', value: patient.mrn }] : [] };

  const observations: any[] = [];
  (series || []).forEach((s: any) => {
    const metric = s.metric || { id: s.metricId, name: s.metricId };
    (s.points || []).forEach((p: any, idx: number) => {
      const obs: any = {
        resourceType: 'Observation',
        id: `obs-${patient.id}-${metric.id}-${idx}`,
        status: 'final',
        category: [{ coding: [{ system: 'http://terminology.hl7.org/CodeSystem/observation-category', code: 'laboratory' }] }],
        code: { text: metric.name },
        subject: { reference: `Patient/${patient.id}`, display: patient.name },
        effectiveDateTime: p.timestamp,
        issued: p.timestamp,
        performer: p.performer ? [{ display: p.performer }] : undefined,
        valueQuantity: { value: typeof p.value === 'number' ? p.value : null, unit: p.unit || metric.unit || undefined },
        interpretation: p.interpretation ? [{ text: p.interpretation }] : undefined,
        encounter: p.encounterId ? { reference: `Encounter/${p.encounterId}` } : undefined,
        note: p.note ? [{ text: p.note }] : undefined,
      };
      observations.push(obs);
    });
  });

  const bundle: any = {
    resourceType: 'Bundle',
    type: 'collection',
    timestamp: now,
    entry: [
      { resource: patientRes },
      ...observations.map((r: any) => ({ resource: r })),
    ],
  };

  return bundle;
}

/**
 * Map a single clinical note to a minimal FHIR Bundle containing a DocumentReference
 * and a Composition resource to represent the note for export.
 */
export function mapNoteToFHIR(patient: any, note: any) {
  const now = new Date().toISOString();

  const patientRes: any = { resourceType: 'Patient', id: patient.id, name: [{ text: patient.name }], birthDate: patient.dob, identifier: patient.mrn ? [{ system: 'urn:mrn', value: patient.mrn }] : [] };

  const composition: any = {
    resourceType: 'Composition',
    id: `composition-${patient.id}-${note.id}`,
    status: 'final',
    type: { text: note.type || note.title || 'Clinical note' },
    subject: { reference: `Patient/${patient.id}`, display: patient.name },
    date: note.date || now,
    author: note.author ? [{ display: note.author }] : undefined,
    title: note.title || (note.snippet ? note.snippet.substring(0, 80) : 'Clinical note'),
    section: [
      {
        title: 'Clinical content',
        text: { status: 'generated', div: `<div>${(note.content || note.snippet || '').replace(/</g, '&lt;')}</div>` },
      },
    ],
  };

  const docRef: any = {
    resourceType: 'DocumentReference',
    id: `docref-${patient.id}-${note.id}`,
    status: 'current',
    type: { text: note.type || 'Progress note' },
    subject: { reference: `Patient/${patient.id}`, display: patient.name },
    date: note.date || now,
    author: note.author ? [{ display: note.author }] : undefined,
    content: [
      {
        attachment: { contentType: 'text/html', data: Buffer.from(note.content || note.snippet || '').toString('base64') },
        title: note.title || 'Clinical note content',
      },
    ],
  };

  const bundle: any = {
    resourceType: 'Bundle',
    type: 'document',
    timestamp: now,
    entry: [
      { resource: patientRes },
      { resource: composition },
      { resource: docRef },
    ],
  };

  return bundle;
}
