const languages: { code: string; name: string }[] = [
  { code: 'en', name: 'English' },
  { code: 'en-GB', name: 'English (UK)' },
  { code: 'es', name: 'Español (Spanish)' },
  { code: 'es-MX', name: 'Español (Mexico)' },
  { code: 'zh-CN', name: '中文 (Chinese, Simplified)' },
  { code: 'zh-TW', name: '中文 (Chinese, Traditional)' },
  { code: 'hi', name: 'हिन्दी (Hindi)' },
  { code: 'ar', name: 'العربية (Arabic)' },
  { code: 'bn', name: 'বাংলা (Bengali)' },
  { code: 'pt', name: 'Português (Portuguese)' },
  { code: 'pt-BR', name: 'Português (Brazil)' },
  { code: 'ru', name: 'Русский (Russian)' },
  { code: 'ja', name: '日本語 (Japanese)' },
  { code: 'pa', name: 'ਪੰਜਾਬੀ (Punjabi)' },
  { code: 'de', name: 'Deutsch (German)' },
  { code: 'fr', name: 'Français (French)' },
  { code: 'id', name: 'Bahasa Indonesia (Indonesian)' },
  { code: 'ur', name: 'اردو (Urdu)' },
  { code: 'mr', name: 'मराठी (Marathi)' },
  { code: 'te', name: 'తెలుగు (Telugu)' },
  { code: 'ta', name: 'தமிழ் (Tamil)' },
  { code: 'vi', name: 'Tiếng Việt (Vietnamese)' },
  { code: 'ko', name: '한국어 (Korean)' },
  { code: 'it', name: 'Italiano (Italian)' },
  { code: 'nl', name: 'Nederlands (Dutch)' },
  { code: 'tr', name: 'Türkçe (Turkish)' },
  { code: 'pl', name: 'Polski (Polish)' },
  { code: 'uk', name: 'Українська (Ukrainian)' },
  { code: 'ro', name: 'Română (Romanian)' },
  { code: 'cs', name: 'Čeština (Czech)' },
  { code: 'el', name: 'Ελληνικά (Greek)' },
  { code: 'hu', name: 'Magyar (Hungarian)' },
  { code: 'sv', name: 'Svenska (Swedish)' },
  { code: 'fi', name: 'Suomi (Finnish)' },
  { code: 'nb', name: 'Norsk bokmål (Norwegian)' },
  { code: 'da', name: 'Dansk (Danish)' },
  { code: 'he', name: 'עברית (Hebrew)' },
  { code: 'th', name: 'ไทย (Thai)' },
  { code: 'ms', name: 'Bahasa Melayu (Malay)' },
  { code: 'sw', name: 'Kiswahili (Swahili)' },
  { code: 'am', name: 'አማርኛ (Amharic)' },
  { code: 'km', name: 'ភាសាខ្មែរ (Khmer)' },
  { code: 'lo', name: 'ພາສາລາວ (Lao)' },
  { code: 'my', name: 'ဗမာ (Burmese)' },
  { code: 'si', name: 'සිංහල (Sinhala)' },
  { code: 'ne', name: 'नेपाली (Nepali)' },
  { code: 'bg', name: 'Български (Bulgarian)' },
  { code: 'sr', name: 'Српски (Serbian)' },
  { code: 'hr', name: 'Hrvatski (Croatian)' },
  { code: 'bs', name: 'Bosanski (Bosnian)' },
  { code: 'sk', name: 'Slovenčina (Slovak)' },
  { code: 'sl', name: 'Slovenščina (Slovenian)' },
  { code: 'mk', name: 'Македонски (Macedonian)' },
  { code: 'sq', name: 'Shqip (Albanian)' },
  { code: 'lv', name: 'Latviešu (Latvian)' },
  { code: 'lt', name: 'Lietuvių (Lithuanian)' },
  { code: 'et', name: 'Eesti (Estonian)' },
  { code: 'ga', name: 'Gaeilge (Irish)' },
  { code: 'is', name: 'Íslenska (Icelandic)' },
  { code: 'mt', name: 'Malti (Maltese)' },
  { code: 'cy', name: 'Cymraeg (Welsh)' },
  { code: 'af', name: 'Afrikaans' },
  { code: 'zu', name: 'isiZulu (Zulu)' },
  { code: 'xh', name: 'isiXhosa (Xhosa)' },
  { code: 'yo', name: 'Yorùbá (Yoruba)' },
  { code: 'ig', name: 'Igbo' },
  { code: 'ha', name: 'Hausa' },
  { code: 'lb', name: 'Lëtzebuergesch (Luxembourgish)' },
  { code: 'be', name: 'Беларуская (Belarusian)' },
  { code: 'kk', name: 'Қазақша (Kazakh)' },
  { code: 'uz', name: 'Oʻzbek (Uzbek)' },
  { code: 'az', name: 'Azərbaycanca (Azerbaijani)' },
  { code: 'hy', name: 'Հայերեն (Armenian)' },
  { code: 'ka', name: 'ქართული (Georgian)' },
  { code: 'mn', name: 'Монгол (Mongolian)' },
  { code: 'ps', name: 'پښتو (Pashto)' },
  { code: 'ku', name: 'Kurdî (Kurdish)' },
  { code: 'fa', name: 'فارسی (Persian / Farsi)' },
  { code: 'sd', name: 'سنڌي (Sindhi)' },
  { code: 'tg', name: 'Тоҷикӣ (Tajik)' },
  { code: 'tk', name: 'Türkmençe (Turkmen)' },
  { code: 'tt', name: 'Татарча (Tatar)' },
  { code: 'uz-Cyrl', name: 'Ўзбекча (Uzbek, Cyrillic)' },
  { code: 'ps-AF', name: 'پښتو (Afghanistan)' },
  { code: 'so', name: 'Soomaaliga (Somali)' },
  { code: 'am-ET', name: 'አማርኛ (Ethiopia)' },
  { code: 'km-KH', name: 'ភាសាខ្មែរ (Cambodia)' },
  { code: 'lg', name: 'Luganda' },
  { code: 'rw', name: 'Kinyarwanda' },
  { code: 'sn', name: 'Shona' },
  { code: 'zu-ZA', name: 'isiZulu (South Africa)' },
  { code: 'st', name: 'Sesotho' },
  { code: 'tn', name: 'Setswana' },
  { code: 'nr', name: 'isiNdebele' },
  { code: 'ss', name: 'siSwati' },
  { code: 'bh', name: 'Bihari' },
  { code: 'mai', name: 'Maithili' },
  { code: 'bho', name: 'Bhojpuri' },
  { code: 'awa', name: 'Awadhi' },
  { code: 'sdh', name: 'Southern Kurdish' },
  { code: 'lez', name: 'Lezgian' },
  { code: 'cv', name: 'Chuvash' },
  { code: 'sah', name: 'Yakut' },
  { code: 'iu', name: 'Inuktitut' },
  { code: 'sm', name: 'Gagana Samoa (Samoan)' },
  { code: 'ty', name: 'Reo Tahiti (Tahitian)' },
  { code: 'fj', name: 'Fijian' },
  { code: 'mi', name: 'Māori' },
  { code: 'tl', name: 'Tagalog (Filipino)' },
  { code: 'ceb', name: 'Cebuano' },
  { code: 'ilo', name: 'Ilocano' },
  { code: 'hmn', name: 'Hmong' }
];

export default languages;
